# profiles.conf — mpv 着色器配置组
# 由 input.conf 中 Alt+1~8 / Ctrl+P 快捷键切换
# 路径全部校验通过，适配 Linux (vulkan)

[FSRCNNX]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/igv/FSRCNNX_x2_8-0-4-1.glsl;~~/shaders/igv/SSimDownscaler.glsl"

[FSRCNNX+]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/igv/FSRCNNX_x2_16-0-4-1.glsl;~~/shaders/igv/SSimDownscaler.glsl"

[NNEDI3]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/nnedi3/gather/nnedi3-nns32-win8x4.glsl;~~/shaders/igv/SSimDownscaler.glsl"

[NNEDI3+]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/nnedi3/gather/nnedi3-nns64-win8x4.glsl;~~/shaders/igv/SSimDownscaler.glsl"

[ravu-zoom]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/ravu/gather/ravu-zoom-ar-r3.glsl;~~/shaders/igv/SSimDownscaler.glsl"

[AnimeJaNai]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/AnimeJaNai/AnimeJaNaiV3L1_HD_x2.glsl"

[Ani4K]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/Ani4k/Ani4Kv2_ArtCNN_C4F32_i2.glsl"

[Anime4K]
profile-restore=copy
glsl-shaders="~~/shaders/igv/KrigBilateral.glsl;~~/shaders/Anime4K/glsl/Restore/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K/glsl/Restore/Anime4K_Restore_CNN_Soft_M.glsl;~~/shaders/Anime4K/glsl/Upscale/Anime4K_Upscale_CNN_x2_S.glsl"
